export const Elements=()=>{
    return{
    emailElement:document.getElementById("email/userName"),
     passwordElement : document.getElementById("password"),
     dashboard : document.getElementById("pageLayout"),
     loginPage: document.getElementById("loginPage"),
     loginButton: document.getElementById("login"),
     error:document.getElementById("errorDisplay"),
     logoutButton:document.getElementById("logout"),
     userNameDOM:document.getElementById('user-login'),
     firstNameDOM:document.getElementById('first-name'),
     lastNameDOM:document.getElementById('last-name'),
     campusDOM:document.getElementById('campus'),
     countryDOM:document.getElementById('country'),
     genderDOM:document.getElementById('gender'),
     joinDateDOM:document.getElementById('created-at'),
     auditRatioDOM:document.getElementById('audit-ratio'), 
     emailDOM:document.getElementById('email'),
     AuditDoneDOM:document.getElementById('audits-done'),
     AuditReceivedDOM:document.getElementById('audits-received'),
     moduleGradeDOM:  document.getElementById('module-grades'),
     piscineGoGradeDOM:document.getElementById('piscine-go-grades'),
     piscineJSGradeDOM:document.getElementById('piscine-js-grades'),
     piscineUXGradeDOM:document.getElementById('piscine-ux-grades'),
     piscineUIGradeDOM:document.getElementById('piscine-ui-grades'),
     modulexpsDOM: document.getElementById('module-xps'),
     goXpsDom:document.getElementById('piscine-go-xps'),
     jsXpsDOM:document.getElementById('piscine-js-xps'),
     uxXpsDOM: document.getElementById('piscine-ux-xps'),
     uiXpsDOM:document.getElementById('piscine-ui-xps'),
     OverallXPDOM:document.getElementById('total-xp')
  
            }
    // return {
    //     email: emailElement ? emailElement.value.trim() : "",
    //     password: passwordElement ? passwordElement.value.trim() : "",
    //     logoutButton,
    //     dashboard,
    //     loginButton,
    //     loginPage,
    //     error,
    //     userNameDOM,
    //     firstNameDOM,
    //     lastNameDOM,
    //     campusDOM,
    //     countryDOM,
    //     genderDOM,joinDateDOM,
    //     auditRatioDOM,
    //     emailDOM,
    //     AuditDoneDOM,
    //     AuditReceivedDOM,
    //     moduleGradeDOM,
    //     piscineGoGradeDOM,
    //     piscineJSGradeDOM,
    //     piscineUIGradeDOM,
    //     piscineUXGradeDOM
    // }
}